### ISSUE TITLE
非南大的同学可以访问测试平台么

### ISSUE THREAD

**Issue by LingZichao** [qmj0923/2020-Fall-NJU-Experiments-in-Digital-Logical-Circuits#1]
同学你好，我看到截图里好像类似OJ的平台，非南大的同学可以注册访问么？或者有没有其他途径进行类似的标准测试？

**Comment by qmj0923** [comment]
> 同学你好，我看到截图里好像类似OJ的平台，非南大的同学可以注册访问么？或者有没有其他途径进行仿真测试？

可以具体说明一下是哪张截图吗？我记得这些实验没有类似OJ那样的测试，自行测试无bug即可。具体来说，即使用Quartus软件进行仿真，以及在FPGA上运行测试。

**Comment by LingZichao** [comment]
> 

感谢回复。在成绩报告里的图片像是OJ测试，应该是我多虑了。

**Comment by qmj0923** [comment]
> > 
> 
> 感谢回复。在成绩报告里的图片像是OJ测试，应该是我多虑了。

这门课的实验成绩由两部分组成：一是按时找助教验收实验，二是完成实验报告。那个平台只是用来提交实验报告，并不是类似OJ系统那样的测试平台。非常感谢你的提问，希望我已经解决了你的疑惑。
